# ruff.toml
target-version = "py312"
line-length = 100

select = ["E", "F", "B", "I", "UP"]
ignore = [
    "E501",  # длина строки (мы уже задаем через line-length)
]

[isort]
known-first-party = ["app"]
combine-as-imports = true
